export interface IData {
    "Município/Posto": string,
    "Ano": string,
    "Mês": string,
    "dia 1": string,
    "dia 2": string,
    "dia 3": string,
    "dia 4": string,
    "dia 5": string,
    "dia 6": string,
    "dia 7": string,
    "dia 8": string,
    "dia 9": string,
    "dia 10": string,
    "dia 11": string,
    "dia 12": string,
    "dia 13": string,
    "dia 14": string,
    "dia 15": string,
    "dia 16": string,
    "dia 17": string,
    "dia 18": string,
    "dia 19": string,
    "dia 20": string,
    "dia 21": string,
    "dia 22": string,
    "dia 23": string,
    "dia 24": string,
    "dia 25": string,
    "dia 26": string,
    "dia 27": string,
    "dia 28": string,
    "dia 29": string,
    "dia 30": string,
    "dia 31": string,
}